server:
  port: 9000
---
spring:
  profiles: LOCAL, default, test
  authKey: mockAuthKey
  datasource:
    url: jdbc:postgresql://localhost:5432/cag_db
    username: cag_admin
    password: ${PSQL_PASSWORD:cag_pass}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
    jpa:
      database: postgresql
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  profiles: WINDOWS
  authKey: mockAuthKey
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/cag_db
    username: cag_admin
    password: ${PSQL_PASSWORD:cag_pass}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
    jpa:
      database: postgresql
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  profiles: PROD
  authKey: mockAuthKey
  datasource:
    url: tbd
    username: cag_admin
    password: ${PSQL_PASSWORD:cag_pass}
  hikari:
    minimum-idle: 2
    maximum-pool-size: 4
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
